import {test} from '@playwright/test';
import {audioFixturePath} from '../audioFixturePath';
import {registerFakeAudioDevicesBeforeEach} from './support/fakeAudioDevices';
import {
    RENDERER_ARMS,
    run60sSmoothnessProbe,
    withChordFanout,
} from './support/smoothness';

// 4-voice "barbershop seven" chord, staccato fixture. Combines the
// rendering load of the dom7 chord (4 simultaneous traces, 4x SAB
// readers / vertex buffers / draw setup) with the gate-transition
// pattern of the staccato fixture (display gate flips at ~3 Hz as
// each tone burst starts and ends). The most punishing rendering
// workload in the suite.
//
// The line-list / single-draw architectural win lives in the
// visual pipeline (compositor present cadence between worker
// submit and pixel-on-screen) which page rAF cannot directly
// observe; this test catches CPU-side regressions under
// articulated workloads (a future change that made the worker
// block main thread, or one that scaled per-channel work
// superlinearly with channel count, would surface here). The
// visual-pipeline finding remains validated by manual
// `?renderer=webgpu` comparison plus in-worker diagnostic logs, not
// by automated assertion.
//
// Single-voice staccato arms were dropped 2026-04-30 in favour of
// the 4-voice chord variant: the prototype's eventual production
// configuration is a four-singer quartet, and under fanout the
// rendering load is 4x while audio-analysis cost is unchanged -
// so the test specifically stresses the rendering layer, which is
// what we care about regression-locking.
//
// The fixture web/test-fixtures/staccato-vowel.wav is a 60 s loop
// of (200 ms 220 Hz tone, 100 ms silence). Generated by
// web/scripts/gen-staccato-audio.mjs.
//
// This file is separate from smoothness.spec.ts because Playwright
// restricts test.use({launchOptions}) to file scope (launchOptions
// force a new worker, which Playwright plans at file-load time).
// Sharing the helper + budgets via support/smoothness.ts keeps the
// two files consistent without duplicating the probe body.

test.use({
    launchOptions: {
        args: [
            '--js-flags=--expose-gc',
            '--enable-precise-memory-info',
            '--autoplay-policy=no-user-gesture-required',
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            `--use-file-for-fake-audio-capture=${audioFixturePath('staccato-vowel.wav')}`,
            '--enable-unsafe-webgpu',
        ],
    },
});

registerFakeAudioDevicesBeforeEach();

for (const arm of RENDERER_ARMS) {
    test(`pitch plot is smooth for 60 seconds (dom7 staccato, ${arm.label})`, {
        tag: '@battery-sensitive',
    }, async ({page}) => {
        await run60sSmoothnessProbe(page, 'dom7-staccato', arm, withChordFanout(arm.querystring));
    });
}
