import {test} from '@playwright/test';
import {join} from 'node:path';
import {
    RENDERER_ARMS,
    registerFakeAudioBeforeEach,
    run60sSmoothnessProbe,
} from './support/smoothness';

// Staccato 60-second smoothness arm. Locks the line-list /
// single-draw architectural win
// (.claude/specs/2026-04-30-webgpu-plot-prototype.md "Architectural
// finding"): the OffscreenCanvas-from-worker bridge on Chromium +
// Windows has per-draw-call sync overhead, not just per-frame.
// Multi-draw line-strip topology produced multi-second visual lag
// under articulated workloads pre-fix; line-list + single draw
// eliminates it. A future regression to multi-draw would surface
// here as elevated p99 / max frame gaps or extra long tasks
// because the bridge sync points compete with the page rAF.
//
// The fixture web/test-fixtures/staccato-vowel.wav is a 60 s loop
// of (200 ms 220 Hz tone, 100 ms silence) - the display gate flips
// at ~3 Hz and the worker walks ~30-50 segments per paint instead
// of one continuous run. Generated by the sibling
// generate-staccato-vowel.mjs script.
//
// This file is separate from smoothness.spec.ts because Playwright
// restricts test.use({launchOptions}) to file scope (it forces a
// new worker, which Playwright plans at file-load time). Sharing
// the helper + budgets via support/smoothness.ts keeps the two
// files consistent without duplicating the probe body.

test.use({
    launchOptions: {
        args: [
            '--js-flags=--expose-gc',
            '--enable-precise-memory-info',
            '--autoplay-policy=no-user-gesture-required',
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            `--use-file-for-fake-audio-capture=${join(import.meta.dirname, '..', 'test-fixtures', 'staccato-vowel.wav')}`,
            '--enable-unsafe-webgpu',
        ],
    },
});

registerFakeAudioBeforeEach();

for (const arm of RENDERER_ARMS) {
    test(`pitch plot is smooth for 60 seconds (staccato, ${arm.label})`, async ({page}) => {
        await run60sSmoothnessProbe(page, 'staccato', arm.label, arm.querystring);
    });
}
